// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ContentManagementSystem.Web.Controllers
{
    public partial class CaptchaController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CaptchaController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CaptchaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual ContentManagementSystem.Commons.Web.Captcha.CaptchaImageResult CaptchaImage()
        {
            return new T4MVC_ContentManagementSystem_Commons_Web_Captcha_CaptchaImageResult(Area, Name, ActionNames.CaptchaImage);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CaptchaController Actions { get { return MVC.Captcha; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Captcha";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Captcha";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CaptchaImage = "CaptchaImage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CaptchaImage = "CaptchaImage";
        }


        static readonly ActionParamsClass_CaptchaImage s_params_CaptchaImage = new ActionParamsClass_CaptchaImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaptchaImage CaptchaImageParams { get { return s_params_CaptchaImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaptchaImage
        {
            public readonly string seed = "seed";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CaptchaController : ContentManagementSystem.Web.Controllers.CaptchaController
    {
        public T4MVC_CaptchaController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CaptchaImageOverride(T4MVC_ContentManagementSystem_Commons_Web_Captcha_CaptchaImageResult callInfo, string seed);

        [NonAction]
        public override ContentManagementSystem.Commons.Web.Captcha.CaptchaImageResult CaptchaImage(string seed)
        {
            var callInfo = new T4MVC_ContentManagementSystem_Commons_Web_Captcha_CaptchaImageResult(Area, Name, ActionNames.CaptchaImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seed", seed);
            CaptchaImageOverride(callInfo, seed);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
