// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ContentManagementSystem.Web.Areas.Dashboard.Controllers
{
    public partial class AdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResetPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Dashboard.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Dashboard";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Details = "Details";
            public readonly string ManageUsers = "ManageUsers";
            public readonly string EducationalDegree = "EducationalDegree";
            public readonly string College = "College";
            public readonly string EducationalGroup = "EducationalGroup";
            public readonly string AcademicRank = "AcademicRank";
            public readonly string DefaultFreeField = "DefaultFreeField";
            public readonly string ActivityLog = "ActivityLog";
            public readonly string AdminMessage = "AdminMessage";
            public readonly string CitationManagement = "CitationManagement";
            public readonly string News = "News";
            public readonly string ResetPassword = "ResetPassword";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Details = "Details";
            public const string ManageUsers = "ManageUsers";
            public const string EducationalDegree = "EducationalDegree";
            public const string College = "College";
            public const string EducationalGroup = "EducationalGroup";
            public const string AcademicRank = "AcademicRank";
            public const string DefaultFreeField = "DefaultFreeField";
            public const string ActivityLog = "ActivityLog";
            public const string AdminMessage = "AdminMessage";
            public const string CitationManagement = "CitationManagement";
            public const string News = "News";
            public const string ResetPassword = "ResetPassword";
        }


        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string info = "info";
        }
        static readonly ActionParamsClass_ManageUsers s_params_ManageUsers = new ActionParamsClass_ManageUsers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageUsers ManageUsersParams { get { return s_params_ManageUsers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageUsers
        {
            public readonly string showDisableUsers = "showDisableUsers";
        }
        static readonly ActionParamsClass_AdminMessage s_params_AdminMessage = new ActionParamsClass_AdminMessage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdminMessage AdminMessageParams { get { return s_params_AdminMessage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdminMessage
        {
            public readonly string showPendingMessages = "showPendingMessages";
        }
        static readonly ActionParamsClass_ResetPassword s_params_ResetPassword = new ActionParamsClass_ResetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPassword ResetPasswordParams { get { return s_params_ResetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPassword
        {
            public readonly string userId = "userId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AcademicRank = "AcademicRank";
                public readonly string ActivityLog = "ActivityLog";
                public readonly string AdminMessage = "AdminMessage";
                public readonly string CitationManagement = "CitationManagement";
                public readonly string College = "College";
                public readonly string DefaultFreeField = "DefaultFreeField";
                public readonly string Details = "Details";
                public readonly string EducationalDegree = "EducationalDegree";
                public readonly string EducationalGroup = "EducationalGroup";
                public readonly string ManageUsers = "ManageUsers";
                public readonly string News = "News";
            }
            public readonly string AcademicRank = "~/Areas/Dashboard/Views/Admin/AcademicRank.cshtml";
            public readonly string ActivityLog = "~/Areas/Dashboard/Views/Admin/ActivityLog.cshtml";
            public readonly string AdminMessage = "~/Areas/Dashboard/Views/Admin/AdminMessage.cshtml";
            public readonly string CitationManagement = "~/Areas/Dashboard/Views/Admin/CitationManagement.cshtml";
            public readonly string College = "~/Areas/Dashboard/Views/Admin/College.cshtml";
            public readonly string DefaultFreeField = "~/Areas/Dashboard/Views/Admin/DefaultFreeField.cshtml";
            public readonly string Details = "~/Areas/Dashboard/Views/Admin/Details.cshtml";
            public readonly string EducationalDegree = "~/Areas/Dashboard/Views/Admin/EducationalDegree.cshtml";
            public readonly string EducationalGroup = "~/Areas/Dashboard/Views/Admin/EducationalGroup.cshtml";
            public readonly string ManageUsers = "~/Areas/Dashboard/Views/Admin/ManageUsers.cshtml";
            public readonly string News = "~/Areas/Dashboard/Views/Admin/News.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminController : ContentManagementSystem.Web.Areas.Dashboard.Controllers.AdminController
    {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            DetailsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ContentManagementSystem.Models.ViewModels.DetailsViewModel info);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(ContentManagementSystem.Models.ViewModels.DetailsViewModel info)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "info", info);
            DetailsOverride(callInfo, info);
            return callInfo;
        }

        [NonAction]
        partial void ManageUsersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool showDisableUsers);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManageUsers(bool showDisableUsers)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageUsers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showDisableUsers", showDisableUsers);
            ManageUsersOverride(callInfo, showDisableUsers);
            return callInfo;
        }

        [NonAction]
        partial void EducationalDegreeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EducationalDegree()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EducationalDegree);
            EducationalDegreeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CollegeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult College()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.College);
            CollegeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EducationalGroupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EducationalGroup()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EducationalGroup);
            EducationalGroupOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AcademicRankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AcademicRank()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AcademicRank);
            AcademicRankOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DefaultFreeFieldOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DefaultFreeField()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DefaultFreeField);
            DefaultFreeFieldOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ActivityLogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActivityLog()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivityLog);
            ActivityLogOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AdminMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool showPendingMessages);

        [NonAction]
        public override System.Web.Mvc.ActionResult AdminMessage(bool showPendingMessages)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdminMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showPendingMessages", showPendingMessages);
            AdminMessageOverride(callInfo, showPendingMessages);
            return callInfo;
        }

        [NonAction]
        partial void CitationManagementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CitationManagement()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CitationManagement);
            CitationManagementOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult News()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.News);
            NewsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int userId);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResetPassword(int userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ResetPasswordOverride(callInfo, userId);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
