// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ContentManagementSystem.Web.Areas.Dashboard.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateNote()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateNote);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CheckPassword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CheckPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SafePassword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SafePassword);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Dashboard.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Dashboard";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Note = "Note";
            public readonly string UpdateNote = "UpdateNote";
            public readonly string TopMenu = "TopMenu";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string Bio = "Bio";
            public readonly string FreePage = "FreePage";
            public readonly string Address = "Address";
            public readonly string Administration = "Administration";
            public readonly string Research = "Research";
            public readonly string Training = "Training";
            public readonly string Studing = "Studing";
            public readonly string Honor = "Honor";
            public readonly string Thesis = "Thesis";
            public readonly string Publication = "Publication";
            public readonly string Workshop = "Workshop";
            public readonly string Language = "Language";
            public readonly string Lesson = "Lesson";
            public readonly string Avatar = "Avatar";
            public readonly string MyAvatar = "MyAvatar";
            public readonly string Details = "Details";
            public readonly string FreeField = "FreeField";
            public readonly string SectionsOrder = "SectionsOrder";
            public readonly string AdminStatistics = "AdminStatistics";
            public readonly string ProfessorStatistics = "ProfessorStatistics";
            public readonly string CheckPassword = "CheckPassword";
            public readonly string SafePassword = "SafePassword";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Note = "Note";
            public const string UpdateNote = "UpdateNote";
            public const string TopMenu = "TopMenu";
            public const string ChangePassword = "ChangePassword";
            public const string Bio = "Bio";
            public const string FreePage = "FreePage";
            public const string Address = "Address";
            public const string Administration = "Administration";
            public const string Research = "Research";
            public const string Training = "Training";
            public const string Studing = "Studing";
            public const string Honor = "Honor";
            public const string Thesis = "Thesis";
            public const string Publication = "Publication";
            public const string Workshop = "Workshop";
            public const string Language = "Language";
            public const string Lesson = "Lesson";
            public const string Avatar = "Avatar";
            public const string MyAvatar = "MyAvatar";
            public const string Details = "Details";
            public const string FreeField = "FreeField";
            public const string SectionsOrder = "SectionsOrder";
            public const string AdminStatistics = "AdminStatistics";
            public const string ProfessorStatistics = "ProfessorStatistics";
            public const string CheckPassword = "CheckPassword";
            public const string SafePassword = "SafePassword";
        }


        static readonly ActionParamsClass_UpdateNote s_params_UpdateNote = new ActionParamsClass_UpdateNote();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateNote UpdateNoteParams { get { return s_params_UpdateNote; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateNote
        {
            public readonly string noteText = "noteText";
        }
        static readonly ActionParamsClass_ChangePassword s_params_ChangePassword = new ActionParamsClass_ChangePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePassword ChangePasswordParams { get { return s_params_ChangePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePassword
        {
            public readonly string previousPassword = "previousPassword";
            public readonly string newPassword = "newPassword";
            public readonly string confirmNewPassword = "confirmNewPassword";
        }
        static readonly ActionParamsClass_Bio s_params_Bio = new ActionParamsClass_Bio();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Bio BioParams { get { return s_params_Bio; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Bio
        {
            public readonly string bio = "bio";
        }
        static readonly ActionParamsClass_FreePage s_params_FreePage = new ActionParamsClass_FreePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FreePage FreePageParams { get { return s_params_FreePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FreePage
        {
            public readonly string freePage = "freePage";
        }
        static readonly ActionParamsClass_Avatar s_params_Avatar = new ActionParamsClass_Avatar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Avatar AvatarParams { get { return s_params_Avatar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Avatar
        {
            public readonly string image = "image";
        }
        static readonly ActionParamsClass_MyAvatar s_params_MyAvatar = new ActionParamsClass_MyAvatar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyAvatar MyAvatarParams { get { return s_params_MyAvatar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyAvatar
        {
            public readonly string withDefault = "withDefault";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string info = "info";
            public readonly string birthdayDate = "birthdayDate";
            public readonly string updateIndex = "updateIndex";
        }
        static readonly ActionParamsClass_SectionsOrder s_params_SectionsOrder = new ActionParamsClass_SectionsOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SectionsOrder SectionsOrderParams { get { return s_params_SectionsOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SectionsOrder
        {
            public readonly string orders = "orders";
        }
        static readonly ActionParamsClass_CheckPassword s_params_CheckPassword = new ActionParamsClass_CheckPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckPassword CheckPasswordParams { get { return s_params_CheckPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckPassword
        {
            public readonly string previousPassword = "previousPassword";
        }
        static readonly ActionParamsClass_SafePassword s_params_SafePassword = new ActionParamsClass_SafePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SafePassword SafePasswordParams { get { return s_params_SafePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SafePassword
        {
            public readonly string newPassword = "newPassword";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AdminDashboardStatistics = "_AdminDashboardStatistics";
                public readonly string _NoteForm = "_NoteForm";
                public readonly string _ProfessorDashboardNotifications = "_ProfessorDashboardNotifications";
                public readonly string _ProfessorDashboardStatistics = "_ProfessorDashboardStatistics";
                public readonly string _SideMenu = "_SideMenu";
                public readonly string _TopMenu = "_TopMenu";
                public readonly string Address = "Address";
                public readonly string Administration = "Administration";
                public readonly string Avatar = "Avatar";
                public readonly string Bio = "Bio";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string Details = "Details";
                public readonly string FreeField = "FreeField";
                public readonly string FreePage = "FreePage";
                public readonly string Honor = "Honor";
                public readonly string Index = "Index";
                public readonly string Language = "Language";
                public readonly string Lesson = "Lesson";
                public readonly string Publication = "Publication";
                public readonly string Research = "Research";
                public readonly string SectionsOrder = "SectionsOrder";
                public readonly string Studing = "Studing";
                public readonly string Thesis = "Thesis";
                public readonly string Training = "Training";
                public readonly string Workshop = "Workshop";
            }
            public readonly string _AdminDashboardStatistics = "~/Areas/Dashboard/Views/Home/_AdminDashboardStatistics.cshtml";
            public readonly string _NoteForm = "~/Areas/Dashboard/Views/Home/_NoteForm.cshtml";
            public readonly string _ProfessorDashboardNotifications = "~/Areas/Dashboard/Views/Home/_ProfessorDashboardNotifications.cshtml";
            public readonly string _ProfessorDashboardStatistics = "~/Areas/Dashboard/Views/Home/_ProfessorDashboardStatistics.cshtml";
            public readonly string _SideMenu = "~/Areas/Dashboard/Views/Home/_SideMenu.cshtml";
            public readonly string _TopMenu = "~/Areas/Dashboard/Views/Home/_TopMenu.cshtml";
            public readonly string Address = "~/Areas/Dashboard/Views/Home/Address.cshtml";
            public readonly string Administration = "~/Areas/Dashboard/Views/Home/Administration.cshtml";
            public readonly string Avatar = "~/Areas/Dashboard/Views/Home/Avatar.cshtml";
            public readonly string Bio = "~/Areas/Dashboard/Views/Home/Bio.cshtml";
            public readonly string ChangePassword = "~/Areas/Dashboard/Views/Home/ChangePassword.cshtml";
            public readonly string Details = "~/Areas/Dashboard/Views/Home/Details.cshtml";
            public readonly string FreeField = "~/Areas/Dashboard/Views/Home/FreeField.cshtml";
            public readonly string FreePage = "~/Areas/Dashboard/Views/Home/FreePage.cshtml";
            public readonly string Honor = "~/Areas/Dashboard/Views/Home/Honor.cshtml";
            public readonly string Index = "~/Areas/Dashboard/Views/Home/Index.cshtml";
            public readonly string Language = "~/Areas/Dashboard/Views/Home/Language.cshtml";
            public readonly string Lesson = "~/Areas/Dashboard/Views/Home/Lesson.cshtml";
            public readonly string Publication = "~/Areas/Dashboard/Views/Home/Publication.cshtml";
            public readonly string Research = "~/Areas/Dashboard/Views/Home/Research.cshtml";
            public readonly string SectionsOrder = "~/Areas/Dashboard/Views/Home/SectionsOrder.cshtml";
            public readonly string Studing = "~/Areas/Dashboard/Views/Home/Studing.cshtml";
            public readonly string Thesis = "~/Areas/Dashboard/Views/Home/Thesis.cshtml";
            public readonly string Training = "~/Areas/Dashboard/Views/Home/Training.cshtml";
            public readonly string Workshop = "~/Areas/Dashboard/Views/Home/Workshop.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : ContentManagementSystem.Web.Areas.Dashboard.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Note()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Note);
            NoteOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateNoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string noteText);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateNote(string noteText)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateNote);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "noteText", noteText);
            UpdateNoteOverride(callInfo, noteText);
            return callInfo;
        }

        [NonAction]
        partial void TopMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopMenu);
            TopMenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ChangePasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string previousPassword, string newPassword, string confirmNewPassword);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword(string previousPassword, string newPassword, string confirmNewPassword)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "previousPassword", previousPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newPassword", newPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "confirmNewPassword", confirmNewPassword);
            ChangePasswordOverride(callInfo, previousPassword, newPassword, confirmNewPassword);
            return callInfo;
        }

        [NonAction]
        partial void BioOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Bio()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Bio);
            BioOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BioOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ContentManagementSystem.Models.ViewModels.BioViewModel bio);

        [NonAction]
        public override System.Web.Mvc.ActionResult Bio(ContentManagementSystem.Models.ViewModels.BioViewModel bio)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Bio);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bio", bio);
            BioOverride(callInfo, bio);
            return callInfo;
        }

        [NonAction]
        partial void FreePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FreePage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FreePage);
            FreePageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FreePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ContentManagementSystem.Models.ViewModels.FreePageViewModel freePage);

        [NonAction]
        public override System.Web.Mvc.ActionResult FreePage(ContentManagementSystem.Models.ViewModels.FreePageViewModel freePage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FreePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "freePage", freePage);
            FreePageOverride(callInfo, freePage);
            return callInfo;
        }

        [NonAction]
        partial void AddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Address()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Address);
            AddressOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AdministrationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Administration()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Administration);
            AdministrationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ResearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Research()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Research);
            ResearchOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TrainingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Training()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Training);
            TrainingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StudingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Studing()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Studing);
            StudingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HonorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Honor()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Honor);
            HonorOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ThesisOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Thesis()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Thesis);
            ThesisOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PublicationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Publication()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Publication);
            PublicationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void WorkshopOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Workshop()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Workshop);
            WorkshopOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LanguageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Language()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Language);
            LanguageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LessonOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Lesson()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lesson);
            LessonOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AvatarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Avatar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Avatar);
            AvatarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AvatarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase image);

        [NonAction]
        public override System.Web.Mvc.ActionResult Avatar(System.Web.HttpPostedFileBase image)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Avatar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image", image);
            AvatarOverride(callInfo, image);
            return callInfo;
        }

        [NonAction]
        partial void MyAvatarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool withDefault);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyAvatar(bool withDefault)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyAvatar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "withDefault", withDefault);
            MyAvatarOverride(callInfo, withDefault);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            DetailsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ContentManagementSystem.Models.ViewModels.DetailsViewModel info, System.DateTime? birthdayDate, string updateIndex);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Details(ContentManagementSystem.Models.ViewModels.DetailsViewModel info, System.DateTime? birthdayDate, string updateIndex)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "info", info);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "birthdayDate", birthdayDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateIndex", updateIndex);
            DetailsOverride(callInfo, info, birthdayDate, updateIndex);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [NonAction]
        partial void FreeFieldOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FreeField()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FreeField);
            FreeFieldOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SectionsOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SectionsOrder()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SectionsOrder);
            SectionsOrderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SectionsOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string[] orders);

        [NonAction]
        public override System.Web.Mvc.ActionResult SectionsOrder(string[] orders)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SectionsOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orders", orders);
            SectionsOrderOverride(callInfo, orders);
            return callInfo;
        }

        [NonAction]
        partial void AdminStatisticsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AdminStatistics()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdminStatistics);
            AdminStatisticsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProfessorStatisticsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProfessorStatistics()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfessorStatistics);
            ProfessorStatisticsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CheckPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string previousPassword);

        [NonAction]
        public override System.Web.Mvc.ActionResult CheckPassword(string previousPassword)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CheckPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "previousPassword", previousPassword);
            CheckPasswordOverride(callInfo, previousPassword);
            return callInfo;
        }

        [NonAction]
        partial void SafePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string newPassword);

        [NonAction]
        public override System.Web.Mvc.ActionResult SafePassword(string newPassword)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SafePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newPassword", newPassword);
            SafePasswordOverride(callInfo, newPassword);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
