// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ContentManagementSystem.Web.Controllers
{
    public partial class ProfileController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProfileController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExternalResearchs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalResearchs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExternalSeminars()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalSeminars);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InternalResearchs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InternalResearchs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InternalSeminars()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InternalSeminars);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FreePage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FreePage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GalleryList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GalleryList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Gallery()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WeeklyProgram()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WeeklyProgram);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GalleryItems()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GalleryItems);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Lessons()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lessons);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Lesson()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lesson);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClassInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PracticeClassInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PracticeClassInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClassImportantDate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassImportantDate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClassNews()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassNews);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClassFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClassPractice()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassPractice);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClassScore()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassScore);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ScopusChartData()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ScopusChartData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GoogleChartData()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GoogleChartData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProfessorAvatar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfessorAvatar);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileController Actions { get { return MVC.Profile; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Profile";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Profile";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string FreeFields = "FreeFields";
            public readonly string Addresses = "Addresses";
            public readonly string Studings = "Studings";
            public readonly string Trainings = "Trainings";
            public readonly string Memberships = "Memberships";
            public readonly string Researchs = "Researchs";
            public readonly string Administrations = "Administrations";
            public readonly string Honors = "Honors";
            public readonly string Theses = "Theses";
            public readonly string Publications = "Publications";
            public readonly string Workshops = "Workshops";
            public readonly string ExternalResearchs = "ExternalResearchs";
            public readonly string ExternalSeminars = "ExternalSeminars";
            public readonly string InternalResearchs = "InternalResearchs";
            public readonly string InternalSeminars = "InternalSeminars";
            public readonly string FreePage = "FreePage";
            public readonly string GalleryList = "GalleryList";
            public readonly string Gallery = "Gallery";
            public readonly string WeeklyProgram = "WeeklyProgram";
            public readonly string GalleryItems = "GalleryItems";
            public readonly string Lessons = "Lessons";
            public readonly string Lesson = "Lesson";
            public readonly string ClassInfo = "ClassInfo";
            public readonly string PracticeClassInfo = "PracticeClassInfo";
            public readonly string ClassImportantDate = "ClassImportantDate";
            public readonly string ClassNews = "ClassNews";
            public readonly string ClassFile = "ClassFile";
            public readonly string ClassPractice = "ClassPractice";
            public readonly string ClassScore = "ClassScore";
            public readonly string ScopusChartData = "ScopusChartData";
            public readonly string GoogleChartData = "GoogleChartData";
            public readonly string Languages = "Languages";
            public readonly string TopMenu = "TopMenu";
            public readonly string ProfessorAvatar = "ProfessorAvatar";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string FreeFields = "FreeFields";
            public const string Addresses = "Addresses";
            public const string Studings = "Studings";
            public const string Trainings = "Trainings";
            public const string Memberships = "Memberships";
            public const string Researchs = "Researchs";
            public const string Administrations = "Administrations";
            public const string Honors = "Honors";
            public const string Theses = "Theses";
            public const string Publications = "Publications";
            public const string Workshops = "Workshops";
            public const string ExternalResearchs = "ExternalResearchs";
            public const string ExternalSeminars = "ExternalSeminars";
            public const string InternalResearchs = "InternalResearchs";
            public const string InternalSeminars = "InternalSeminars";
            public const string FreePage = "FreePage";
            public const string GalleryList = "GalleryList";
            public const string Gallery = "Gallery";
            public const string WeeklyProgram = "WeeklyProgram";
            public const string GalleryItems = "GalleryItems";
            public const string Lessons = "Lessons";
            public const string Lesson = "Lesson";
            public const string ClassInfo = "ClassInfo";
            public const string PracticeClassInfo = "PracticeClassInfo";
            public const string ClassImportantDate = "ClassImportantDate";
            public const string ClassNews = "ClassNews";
            public const string ClassFile = "ClassFile";
            public const string ClassPractice = "ClassPractice";
            public const string ClassScore = "ClassScore";
            public const string ScopusChartData = "ScopusChartData";
            public const string GoogleChartData = "GoogleChartData";
            public const string Languages = "Languages";
            public const string TopMenu = "TopMenu";
            public const string ProfessorAvatar = "ProfessorAvatar";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_ExternalResearchs s_params_ExternalResearchs = new ActionParamsClass_ExternalResearchs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExternalResearchs ExternalResearchsParams { get { return s_params_ExternalResearchs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExternalResearchs
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ExternalSeminars s_params_ExternalSeminars = new ActionParamsClass_ExternalSeminars();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExternalSeminars ExternalSeminarsParams { get { return s_params_ExternalSeminars; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExternalSeminars
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_InternalResearchs s_params_InternalResearchs = new ActionParamsClass_InternalResearchs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InternalResearchs InternalResearchsParams { get { return s_params_InternalResearchs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InternalResearchs
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_InternalSeminars s_params_InternalSeminars = new ActionParamsClass_InternalSeminars();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InternalSeminars InternalSeminarsParams { get { return s_params_InternalSeminars; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InternalSeminars
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_FreePage s_params_FreePage = new ActionParamsClass_FreePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FreePage FreePageParams { get { return s_params_FreePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FreePage
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_GalleryList s_params_GalleryList = new ActionParamsClass_GalleryList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GalleryList GalleryListParams { get { return s_params_GalleryList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GalleryList
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_Gallery s_params_Gallery = new ActionParamsClass_Gallery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Gallery GalleryParams { get { return s_params_Gallery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Gallery
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
            public readonly string title = "title";
        }
        static readonly ActionParamsClass_WeeklyProgram s_params_WeeklyProgram = new ActionParamsClass_WeeklyProgram();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WeeklyProgram WeeklyProgramParams { get { return s_params_WeeklyProgram; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WeeklyProgram
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_GalleryItems s_params_GalleryItems = new ActionParamsClass_GalleryItems();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GalleryItems GalleryItemsParams { get { return s_params_GalleryItems; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GalleryItems
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Lessons s_params_Lessons = new ActionParamsClass_Lessons();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Lessons LessonsParams { get { return s_params_Lessons; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Lessons
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_Lesson s_params_Lesson = new ActionParamsClass_Lesson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Lesson LessonParams { get { return s_params_Lesson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Lesson
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
            public readonly string title = "title";
        }
        static readonly ActionParamsClass_ClassInfo s_params_ClassInfo = new ActionParamsClass_ClassInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClassInfo ClassInfoParams { get { return s_params_ClassInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClassInfo
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PracticeClassInfo s_params_PracticeClassInfo = new ActionParamsClass_PracticeClassInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PracticeClassInfo PracticeClassInfoParams { get { return s_params_PracticeClassInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PracticeClassInfo
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClassImportantDate s_params_ClassImportantDate = new ActionParamsClass_ClassImportantDate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClassImportantDate ClassImportantDateParams { get { return s_params_ClassImportantDate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClassImportantDate
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClassNews s_params_ClassNews = new ActionParamsClass_ClassNews();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClassNews ClassNewsParams { get { return s_params_ClassNews; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClassNews
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClassFile s_params_ClassFile = new ActionParamsClass_ClassFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClassFile ClassFileParams { get { return s_params_ClassFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClassFile
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClassPractice s_params_ClassPractice = new ActionParamsClass_ClassPractice();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClassPractice ClassPracticeParams { get { return s_params_ClassPractice; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClassPractice
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClassScore s_params_ClassScore = new ActionParamsClass_ClassScore();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClassScore ClassScoreParams { get { return s_params_ClassScore; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClassScore
        {
            public readonly string pageId = "pageId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ScopusChartData s_params_ScopusChartData = new ActionParamsClass_ScopusChartData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ScopusChartData ScopusChartDataParams { get { return s_params_ScopusChartData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ScopusChartData
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_GoogleChartData s_params_GoogleChartData = new ActionParamsClass_GoogleChartData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GoogleChartData GoogleChartDataParams { get { return s_params_GoogleChartData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GoogleChartData
        {
            public readonly string pageId = "pageId";
        }
        static readonly ActionParamsClass_ProfessorAvatar s_params_ProfessorAvatar = new ActionParamsClass_ProfessorAvatar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProfessorAvatar ProfessorAvatarParams { get { return s_params_ProfessorAvatar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProfessorAvatar
        {
            public readonly string pageId = "pageId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Addresses = "_Addresses";
                public readonly string _Administrations = "_Administrations";
                public readonly string _ClassInfo = "_ClassInfo";
                public readonly string _ExternalResearchs = "_ExternalResearchs";
                public readonly string _ExternalSeminars = "_ExternalSeminars";
                public readonly string _FreeFields = "_FreeFields";
                public readonly string _GalleryItem = "_GalleryItem";
                public readonly string _Honors = "_Honors";
                public readonly string _InternalArticles = "_InternalArticles";
                public readonly string _InternalSeminars = "_InternalSeminars";
                public readonly string _Languages = "_Languages";
                public readonly string _LessonFile = "_LessonFile";
                public readonly string _LessonImportantDate = "_LessonImportantDate";
                public readonly string _LessonNews = "_LessonNews";
                public readonly string _LessonPractice = "_LessonPractice";
                public readonly string _LessonScore = "_LessonScore";
                public readonly string _Memberships = "_Memberships";
                public readonly string _PracticeClass = "_PracticeClass";
                public readonly string _Publications = "_Publications";
                public readonly string _Researchs = "_Researchs";
                public readonly string _Studings = "_Studings";
                public readonly string _Theses = "_Theses";
                public readonly string _TopMenu = "_TopMenu";
                public readonly string _Trainings = "_Trainings";
                public readonly string _Workshops = "_Workshops";
                public readonly string FreePage = "FreePage";
                public readonly string Gallery = "Gallery";
                public readonly string GalleryList = "GalleryList";
                public readonly string Index = "Index";
                public readonly string Lesson = "Lesson";
                public readonly string Lessons = "Lessons";
                public readonly string WeeklyProgram = "WeeklyProgram";
            }
            public readonly string _Addresses = "~/Views/Profile/_Addresses.cshtml";
            public readonly string _Administrations = "~/Views/Profile/_Administrations.cshtml";
            public readonly string _ClassInfo = "~/Views/Profile/_ClassInfo.cshtml";
            public readonly string _ExternalResearchs = "~/Views/Profile/_ExternalResearchs.cshtml";
            public readonly string _ExternalSeminars = "~/Views/Profile/_ExternalSeminars.cshtml";
            public readonly string _FreeFields = "~/Views/Profile/_FreeFields.cshtml";
            public readonly string _GalleryItem = "~/Views/Profile/_GalleryItem.cshtml";
            public readonly string _Honors = "~/Views/Profile/_Honors.cshtml";
            public readonly string _InternalArticles = "~/Views/Profile/_InternalArticles.cshtml";
            public readonly string _InternalSeminars = "~/Views/Profile/_InternalSeminars.cshtml";
            public readonly string _Languages = "~/Views/Profile/_Languages.cshtml";
            public readonly string _LessonFile = "~/Views/Profile/_LessonFile.cshtml";
            public readonly string _LessonImportantDate = "~/Views/Profile/_LessonImportantDate.cshtml";
            public readonly string _LessonNews = "~/Views/Profile/_LessonNews.cshtml";
            public readonly string _LessonPractice = "~/Views/Profile/_LessonPractice.cshtml";
            public readonly string _LessonScore = "~/Views/Profile/_LessonScore.cshtml";
            public readonly string _Memberships = "~/Views/Profile/_Memberships.cshtml";
            public readonly string _PracticeClass = "~/Views/Profile/_PracticeClass.cshtml";
            public readonly string _Publications = "~/Views/Profile/_Publications.cshtml";
            public readonly string _Researchs = "~/Views/Profile/_Researchs.cshtml";
            public readonly string _Studings = "~/Views/Profile/_Studings.cshtml";
            public readonly string _Theses = "~/Views/Profile/_Theses.cshtml";
            public readonly string _TopMenu = "~/Views/Profile/_TopMenu.cshtml";
            public readonly string _Trainings = "~/Views/Profile/_Trainings.cshtml";
            public readonly string _Workshops = "~/Views/Profile/_Workshops.cshtml";
            public readonly string FreePage = "~/Views/Profile/FreePage.cshtml";
            public readonly string Gallery = "~/Views/Profile/Gallery.cshtml";
            public readonly string GalleryList = "~/Views/Profile/GalleryList.cshtml";
            public readonly string Index = "~/Views/Profile/Index.cshtml";
            public readonly string Lesson = "~/Views/Profile/Lesson.cshtml";
            public readonly string Lessons = "~/Views/Profile/Lessons.cshtml";
            public readonly string WeeklyProgram = "~/Views/Profile/WeeklyProgram.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProfileController : ContentManagementSystem.Web.Controllers.ProfileController
    {
        public T4MVC_ProfileController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            IndexOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void FreeFieldsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FreeFields()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FreeFields);
            FreeFieldsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddressesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Addresses()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Addresses);
            AddressesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StudingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Studings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Studings);
            StudingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TrainingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Trainings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Trainings);
            TrainingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MembershipsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Memberships()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Memberships);
            MembershipsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ResearchsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Researchs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Researchs);
            ResearchsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AdministrationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Administrations()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Administrations);
            AdministrationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HonorsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Honors()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Honors);
            HonorsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ThesesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Theses()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Theses);
            ThesesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PublicationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Publications()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Publications);
            PublicationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void WorkshopsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Workshops()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Workshops);
            WorkshopsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ExternalResearchsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExternalResearchs(string pageId, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalResearchs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExternalResearchsOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ExternalSeminarsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExternalSeminars(string pageId, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalSeminars);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExternalSeminarsOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void InternalResearchsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InternalResearchs(string pageId, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InternalResearchs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InternalResearchsOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void InternalSeminarsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InternalSeminars(string pageId, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InternalSeminars);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InternalSeminarsOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void FreePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult FreePage(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FreePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            FreePageOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void GalleryListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GalleryList(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GalleryList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            GalleryListOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void GalleryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id, string title);

        [NonAction]
        public override System.Web.Mvc.ActionResult Gallery(string pageId, long id, string title)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Gallery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "title", title);
            GalleryOverride(callInfo, pageId, id, title);
            return callInfo;
        }

        [NonAction]
        partial void WeeklyProgramOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult WeeklyProgram(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WeeklyProgram);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            WeeklyProgramOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void GalleryItemsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GalleryItems(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GalleryItems);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GalleryItemsOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void LessonsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Lessons(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lessons);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            LessonsOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void LessonOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id, string title);

        [NonAction]
        public override System.Web.Mvc.ActionResult Lesson(string pageId, long id, string title)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Lesson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "title", title);
            LessonOverride(callInfo, pageId, id, title);
            return callInfo;
        }

        [NonAction]
        partial void ClassInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClassInfo(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClassInfoOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void PracticeClassInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PracticeClassInfo(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PracticeClassInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PracticeClassInfoOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ClassImportantDateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClassImportantDate(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassImportantDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClassImportantDateOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ClassNewsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClassNews(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassNews);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClassNewsOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ClassFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClassFile(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClassFileOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ClassPracticeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClassPractice(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassPractice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClassPracticeOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ClassScoreOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClassScore(string pageId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClassScore);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClassScoreOverride(callInfo, pageId, id);
            return callInfo;
        }

        [NonAction]
        partial void ScopusChartDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ScopusChartData(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ScopusChartData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ScopusChartDataOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void GoogleChartDataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GoogleChartData(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GoogleChartData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            GoogleChartDataOverride(callInfo, pageId);
            return callInfo;
        }

        [NonAction]
        partial void LanguagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Languages()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Languages);
            LanguagesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TopMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopMenu);
            TopMenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProfessorAvatarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string pageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProfessorAvatar(string pageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfessorAvatar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageId", pageId);
            ProfessorAvatarOverride(callInfo, pageId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
