// <auto-generated />
namespace ContentManagementSystem.DataLayer.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added5FieldsToTraining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added5FieldsToTraining));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191542367_Added5FieldsToTraining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
